### ISSUE TITLE
Xaraya Security Vulnerabilities Notification

### ISSUE THREAD

**Issue by HTBridge** [xaraya/core#1]
Hello,

High-Tech Bridge Security Research Lab has discovered multiple security vulnerabilities in Xaraya 2.4.0-b1

Preview available here: https://www.htbridge.com/advisory/HTB23156

Developers can contact us by email for details: advisory (at) htbridge.com

For any questions related to this notification message - please visit our General Information & Disclosure Policy page: https://www.htbridge.com/advisory/disclosure_policy.html

Best regards,

High-Tech Bridge Security Research Lab

**Comment by xaraya** [comment]
Fixed
