### ISSUE TITLE
Calling assert() with a string argument is deprecated in PHP 7.2

### ISSUE THREAD

**Issue by mikespub** [xaraya/core#19]
I didn't  know how you wanted to resolve this - keep compatibility with PHP 5.x and 7.1- or not - so I didn't push any changes

**Comment by mikespub** [comment]
Cleaned up in https://github.com/xaraya/core/commit/5cc6407790b212019a29ee024bdad20822f89963 and later - thanks :-)

**Comment by xaraya** [comment]
Yeah, sorry for the assert() f..up yesterday
