### ISSUE TITLE
creating v2.4.0 release + adding to packagist

### ISSUE THREAD

**Issue by mikespub** [xaraya/core#40]
I've created a base v2.4.0 release here on GitHub and added a ["xaraya/core"](https://packagist.org/packages/xaraya/core) composer package at https://packagist.org/

Feel free to take over there anytime, as I don't have the right to set up GitHub hooks for automatic updates :-)

**Comment by xaraya** [comment]
Sorry for not keeping up here. What needs to be done here to get you the permissions you need?

**Comment by mikespub** [comment]
I'm not quite sure actually. You could register & take over ownership of the package on Packagist yourself :-)

Or if you don't want to bother with it, you may need to allow Packagist access to the organization as mentioned at https://packagist.org/about#how-to-update-packages

And/or it may be enough to grant me admin access to the repo as the error message indicates when I try to activate automatic updates:
Hooks setup failures
[xaraya/core](https://packagist.org/packages/xaraya/core) GitHub user has no admin access to the repository, or Packagist was not granted access to the organization ([check here](https://github.com/settings/connections/applications/a059f127e1c09c04aa5a))

No big worries though - since we don't seem to be updating this very often anyway, I can always trigger an update manually...

**Comment by mikespub** [comment]
Clean-up old issues
