### ISSUE TITLE
Possible bug in source code (CWE-398)

### ISSUE THREAD

**Issue by AppChecker** [xaraya/core#6]
Hello!

We've checked your code with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php) and found possible bug:

https://github.com/xaraya/core/blob/9cbd95b5d96ecc7440aeab56494a3924e7abd9ec/html/code/modules/roles/xaradmin/sendmail.php#L25

```
    if (!xarVarFetch('id',     'int:0:', $id, 0)) return;
    if (!xarVarFetch('state',   'int:0:', $state, xarRoles::ROLES_STATE_CURRENT)) return;
    if (!xarVarFetch('message', 'str:1:', $message,'')) return;
    if (!xarVarFetch('subject', 'str:1',  $subject, '')) return;
    if (!xarVarFetch('includesubgroups','int:0:',$includesubgroups,0,XARVAR_NOT_REQUIRED));
```
The last if-statement is empty. Maybe there must be return like in others.

Possible defect was found by Echelon Team with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by xaraya** [comment]
Pushed a fix
