### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [xaraya/core#60]
Dear @xaraya team, @random777, @mrvdb, @mikespub, @paramss, @godboko, @rolfmeijer, @CaraesNaur, @psspl1998, @ano7, @developweb10, @ftb,

It will be nice to remove old parts like:
- https://sourceforge.net/p/xaraya/news/

Can you add a "move" box like https://sourceforge.net/projects/mumble for example:
- https://sourceforge.net/p/xaraya/

Please replace the website by the GitHub (https://github.com/xaraya):
- https://sourceforge.net/projects/xaraya/
- https://sourceforge.net/projects/xaraya/support

Keep only the GitHub (https://github.com/xaraya):
- https://sourceforge.net/p/xaraya/_list/link

To disable/delete tabs, go here: https://sourceforge.net/projects/xaraya/
To add a new tab, go here: https://sourceforge.net/projects/xaraya/
To change informations, go here: https://sourceforge.net/p/xaraya/admin/overview
To export, go here: https://sourceforge.net/p/xaraya/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/xaraya/admin/overview
- A new tab, go here: https://sourceforge.net/projects/xaraya/

Thanks in advance.

**Comment by mikespub** [comment]
@Neustradamus seems to have some automated action submitting random issues to multiple repositories
This issue is irrelevant

**Comment by Neustradamus** [comment]
@mikespub: I am not a bot, please reopen this ticket, the problem is not solved.
Thanks in advance.
