### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [xaraya/core#62]
Dear @xaraya team, @random777, @mrvdb, @mikespub, @paramss, @godboko, @rolfmeijer, @CaraesNaur, @psspl1998, @ano7, @developweb10, @ftb,

It will be nice to remove old parts like:
- https://sourceforge.net/p/xaraya/news/

Can you add a "move" box like https://sourceforge.net/projects/mumble for example:
- https://sourceforge.net/p/xaraya/

Please replace the website by the GitHub (https://github.com/xaraya):
- https://sourceforge.net/projects/xaraya/
- https://sourceforge.net/projects/xaraya/support

Keep only the GitHub (https://github.com/xaraya):
- https://sourceforge.net/p/xaraya/_list/link

To disable/delete tabs, go here: https://sourceforge.net/projects/xaraya/
To add a new tab, go here: https://sourceforge.net/projects/xaraya/
To change informations, go here: https://sourceforge.net/p/xaraya/admin/overview
To export, go here: https://sourceforge.net/p/xaraya/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/xaraya/admin/overview
- A new tab, go here: https://sourceforge.net/projects/xaraya/

Thanks in advance.

There was a previous ticket but one guy has closed it without solution:
- https://github.com/xaraya/core/issues/60

**Comment by mikespub** [comment]
See #61

**Comment by Neustradamus** [comment]
@mikespub: Please do not close an unsolved ticket, please reopen.

Who has rights on the xaraya personal account?
What is the email address linked?
Who has added you some rights on this repository?

Thanks in advance.

**Comment by Neustradamus** [comment]
@mikespub: Please do not close an unsolved ticket, please reopen.

Who has rights on the xaraya personal account?
What is the email address linked?
Who has added you some rights on this repository?

You can see here the team on Sourceforge:
- Xaraya: https://sourceforge.net/p/xaraya/_members/
- Modules: https://sourceforge.net/p/xarayamodules/_members/
- Themes: https://sourceforge.net/p/xarayathemes/_members/

Thanks in advance.

**Comment by CaraesNaur** [comment]
@Neustradamus I'm going to defer to @mikespub for all things Xaraya since he seems to be the only person still active.  If he asks me to do anything specific, I'll make an effort to try.

My SourceForge account is tied to a dead email address, so I can't help with any of that.

**Comment by mikespub** [comment]
Hi @Neustradamus

Let me try to explain once again - Sourceforge is not and has never been the master of the Xaraya source code, it's only an outdated copy & file distribution from more than 10 years ago.

So there is absolutely no reason to migrate that old stuff, unless you want to keep it for personal reasons - in which case, feel free to fork it yourself.

**Comment by Neustradamus** [comment]
Dear all,

Thanks for your answer @CaraesNaur, I have sent you an e-mail with a link to recover your account.
I can help all other members too.

I have been blocked from https://github.com/xaraya-modules by @mikespub, can you unblock me?

I think he has not understood. It is to inform all people that the recent code is on GitHub.
All other projects have done it.

Thanks in advance.

**Comment by CaraesNaur** [comment]
I cannot receive that email.  That SF account is older than GMail... it is most likely tied to one of my dormant domains which I have no current plans to restore.

I will not take any administrative action on the Xaraya GitHub because I am no longer involved with the project.

Just leave it alone.
